In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr) # to print array
print(type(arr))#To check array type class

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr = np.array((1,2,3,4,5)) # We can pass tuple in array.
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Array

In [4]:
arr = np.array(20) # 0 Dimension array
print(arr)
print(type(arr))
print(arr.ndim) # To know the dimension of array

20
<class 'numpy.ndarray'>
0


# 1 D Array

In [5]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


# 2 D Array

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [7]:
arr = np.array([[1.1,2.2,3.3],[4.1,5.1,6.1]]) # We can take float number in array creation.
print(arr)
print(type(arr))
print(arr.ndim)


[[1.1 2.2 3.3]
 [4.1 5.1 6.1]]
<class 'numpy.ndarray'>
2


# 3 D Array

In [8]:
arr = np.array([[[1,2,3],[4,5,6],[1,2,3]],[[7,8,9],[10,11,12],[12,21,33]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 1  2  3]]

 [[ 7  8  9]
  [10 11 12]
  [12 21 33]]]
<class 'numpy.ndarray'>
3


In [9]:
arr = np.array([[[1,2,3],[2,1,3],[1,22,33]],[[1,2,3],[1,2,3],[1,2,3]]])
print(arr)
print(type(arr))
print(arr.ndim)


[[[ 1  2  3]
  [ 2  1  3]
  [ 1 22 33]]

 [[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]]]
<class 'numpy.ndarray'>
3


In [10]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
<class 'numpy.ndarray'>
3


In [11]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3


In [12]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3


In [13]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3


In [14]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3


# Create an array with 5 dimensions and verify that it has 5 dimension

In [15]:
arr = np.array([1,2,3,4],ndmin = 5) # To create 5d array use a keyword = "ndmin"
print(arr)
print(type(arr))
print(arr.ndim)

[[[[[1 2 3 4]]]]]
<class 'numpy.ndarray'>
5


In [16]:
arr = np.array([23,234,34,56,],ndmin = 6)
print(arr)
print(type(arr))
print(arr.ndim)

[[[[[[ 23 234  34  56]]]]]]
<class 'numpy.ndarray'>
6


# Indexing in NumPy Array

In [17]:
arr = np.array([23,34,45,56,67,78,89,90])
print(arr)
print(type(arr))
print(arr.ndim)

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[5])
print(arr[6])
print(arr[7])

[23 34 45 56 67 78 89 90]
<class 'numpy.ndarray'>
1
23
34
45
56
67
78
89
90


# Get 3rd,6th and 8th elements from the following array and add them.

In [18]:
m = np.array([41,87,34,56,39,90,15,10,19,56])
print(arr)
print(type(arr))
print(arr.ndim)
print(m[2])
print(m[5])
print(m[7])
print("sum of the element", m[2]+m[3]+m[5]+m[7])

[23 34 45 56 67 78 89 90]
<class 'numpy.ndarray'>
1
34
90
10
sum of the element 190


# Accessing 2D Arrays

In [19]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0,1]) # first row second element

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
<class 'numpy.ndarray'>
2
20


In [20]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0,3]) #First row 4th element

40


In [21]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[1,0]) # First element 2nd row

60


In [22]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[1,4])

100


# Add the first element of row 1 and last element of second row.

In [23]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("sum is",arr[0,1]+(arr[1,4]))

sum is 120


# Accessing 3D element from Arrays

In [24]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)
print(arr[1,1])
print(arr[1,1,0])
print(arr[1,0,1])
print(arr[0,0,0])


3
[10 11 12]
10
8
1


# Slicing Of Numpy Arrays

In [25]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr.ndim)
print(type(arr))

print(arr[1:5:1])
print(arr[0:7:2])

[1 2 3 4 5 6 7]
1
<class 'numpy.ndarray'>
[2 3 4 5]
[1 3 5 7]


# Slicing In 2D Arrays

In [26]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(type(arr))
print(arr.ndim)
print(arr)

print(arr[1::,1:4:1])
print(arr[0,0:3:1])

<class 'numpy.ndarray'>
2
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[70 80 90]]
[10 20 30]


# Data Types In NumPy
# Numpy has some extra data types, and refer to data types with one character.
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# o - object
# s - string
# u - unicode string
# v - fixed chunk of memory for other type (viod)

                                  **checking the data type of an array**

In [27]:
arr = np.array([1,2,3,4])
print(arr.dtype) #checking data type

int64


In [28]:
arr = np.array(['animals','bat','cat'])
print(arr.dtype)

<U7


# Creating Arrays with a defined data type

In [29]:
arr = np.array([1,2,3,4], dtype = 'S') #For sting use capital 'S'
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Create An Array with data type 4bytes integer

In [30]:
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Numpy Array Shape

The shape of an array is the number of elements in each dimension

In [31]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.dtype)
print(arr.shape)# showing dimensions and no of elements in each dimension

[[1 2 3 4]
 [5 6 7 8]]
int64
(2, 4)


In [32]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(arr.shape)

(1, 3, 4)


# Concatenate NumPy Arrays

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


 # Concatenating 2D Arrays

In [34]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr= np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [35]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr= np.concatenate((arr1,arr2),axis = 0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting Numpy Array

In [36]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# Splitting Arrays in 4 Parts

In [37]:
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [38]:
newarr = np.array_split(arr,10)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [39]:
newarr = np.array_split(arr,20)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


# ravel And flatten

converts multidimensional into 1d array

In [40]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
m = arr.ravel() # convert into 1D
print(m)
print(m.ndim)
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3 4 5 6 7 8 9]
1
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Unique Function

In [41]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10]))


In [42]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True, return_counts = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10]), array([2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1]))


# Delete Function()

In [43]:
a = np.array([12,13,14,15])
d = np. delete(a,[1])
print(d)


[12 14 15]


In [44]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
x.ndim
print(x)
m = np.delete(x,0,axis = 0)
print(m)


[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]
[[ 4  5  7  1  2]
 [50  0 65  6  7]]
